apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakF4TWpVeQpNVE0xTlRoYUZ3MDBNakF4TWpVeU1UTTFOVGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNTRtVHpoVy9yT1o2cEg3VjZ2MzR0WXZ0MGloZzRsdWttOG5wWXRJVmh6V3dIR1hSeQpNdDFwQk9mcHVUL05ubnlYcUp5T1doc1MzTHY3SmNpQnpxdGx0dEgvV2R1ZnFUQldOekovYThqQ1QvSjJHOXF3CkpxN1MyOTlyOUxITENZWVp3c05pMEZSQ0M4ZFhrWCs4Uk55cnFlREJ5T1VjZDBlUVdaaEZSaHVRemZRU2ttcDEKOWV1NnRpWHdCaVV1R3JKOElGSGM2UEFQVkJuekFvZkJBWCt3NnZ3ZkNBQXMwbnE1KzhzbzNDNDZ1RFordVlPdApsbnJWcS9mejNkTUtaYWIwNUJ4Y2hJZU0wbll1bmJEaFlPand6SDVCS2tQd2IrNkxZUHJQL3VKL1VZUGdrTUViCkRjTDRZTlN2Q3JlNkdsSlFCTkFnU1NZSlZuMWJmZHNYWlRoN0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNsOXdpdzM4a09RZjBSOTlnTwpnLzVSKzJXOGJ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFjbjZCOWZ5ZU9GTUxwWXRiN2JTWFdaTVlPYU5JCmpkcDNIMlBzemZpb2FLSjF4d2M5RWxOekVQRXBpSXhKVWJUcHJaRlNXRXhocUQxcnkyZG5VUmlMYkNNWE4yOE0KaXRmUkNwY0xHYVZBWTdsdkw4MHRlT0EvZ1g1M0toRmRaTmtrczFueU9Md2ltS21wa1lhQndiVlZJcUpQdi9vQQpkT1kxbm43YlVqYkNvN1QvaU5WQVNsOHYvUFloTlltTm5ZaEQ3NE5sZzdzZFpXdk9RaGNQN3JWdStqZEhIUWNBCjZBSVJveVhjYm90cHRodTNZaDZrSmgxbVREcXQyYVR3VkhJZUY5bi96ZVZFNzJwdjNyYzNNcnUvdjMxV2N6d3YKM3RCOGZrOWoyS2U3c1RZWlZZQW9MYzdBL2I5VFhtZzlMY250QXBlUmRaRjh6RzR1WG9YSERxeStUQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9338b70b-d4e6-4ab4-9885-854082b96ac2.k8s.ondigitalocean.com
  name: do-nyc1-k8s-helm
contexts:
- context:
    cluster: do-nyc1-k8s-helm
    user: do-nyc1-k8s-helm-admin
  name: do-nyc1-k8s-helm
current-context: do-nyc1-k8s-helm
users:
- name: do-nyc1-k8s-helm-admin
  user:
    token: e2e3f166ea541bf376cc66cfde4962ec3dbf3244ba021089a7a5a392eb661e9d
