# Service do MongoDB

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-service
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}-mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP