# Deployment da aplicação web Rotten Potatoes

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Release.Name }}-web
    spec:
      containers:
      - name: web
        image: {{ .Values.web.image }}:{{ .Values.web.tag }}
        ports:
        - containerPort: 5000        
        env:
        - name: MONGODB_DB
          value: {{ .Values.web.mongoDatabase }}
        - name: MONGODB_HOST
          value: {{ .Release.Name }}-mongodb-service
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: {{ .Values.mongodb.user }}
        - name: MONGODB_PASSWORD
          value: {{ .Values.mongodb.password }}
        # Boas práticas para Deplpy no Container 
        # livenesseProbe para quando o CÓDIGO pode não estar saudável, sem precisar matar e subir o container na mão
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        #ReadinessProbe para quando o container não está pronto.
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
        #resources:
         # limits:
          #  cpu: "0.2"
          #  memory: "32Mi"
         # requests:
          #  cpu: "0.1"
          #  memory: "24Mi"         