name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./rotten-potatoes/src
          file: ./rotten-potatoes/src/Dockerfile
          push: true
          tags: |
            viniciusesteter/rotten-potatoes:latest
            viniciusesteter/rotten-potatoes:${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - name: Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
    # The kind version to use (default: v0.11.1)
          version: v0.11.1
    # The path to the kind config file
          config: k8s
    # The Docker image for the cluster nodes
          node_image: viniciusesteter/rotten-potatoes:${{ github.run_number }}
    # The name of the cluster to create (default: chart-testing)
          cluster_name: Helm-Cluster
    # The duration to wait for the control plane to become ready (default: 60s)
          wait: 60s
    # The log level for kind
          log_level: 0
     
