name: CI-CD

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./rotten-potatoes/src
          file: ./rotten-potatoes/src/Dockerfile
          push: true
          tags: |
            viniciusesteter/rotten-potatoes:latest
            viniciusesteter/rotten-potatoes:${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes Helm Kubeval
  # You may pin to the exact commit or the version.
  # uses: wiremind/helm-kubeval-action@eff33cfdeb169620c03661bf6dee4257775eb047
        uses: wiremind/helm-kubeval-action@v1.2.1
        with:
    # The path to the directory containing your Chart(s)
          path: ./rotten-potetoes/rotten-potetoes
    # The path to the configuration file containing your Chart(s) Repository Url(s)
          config: config_repos
    # Output format for results
          output: stdout
    # Version of Kubernetes to validate against
          version: master
    # Whether to not to check for extra properties
          strict: true
    # Whether to use the schemas from OpenShift rather than Kubernetes
          openshift: false
    # Whether or not to skip custom resources
          ignore_missing_schemas: true
